#let tiempo = "Ordinario"
#let domingo_num = 26
#let fecha = "2026-09-27"
#let frase = "¿Crees que Dios puede perdonar a cualquiera que se arrepienta?"

#let monicion_entrada = [Jesús hoy nos pregunta si nuestra fe se queda en palabras o realmente transforma nuestra vida. Dispongamos el corazón para pasar del “sí” dicho al “sí” vivido.]
#let monicion_ofrendas = [Que nuestra ofrenda sea un “sí” concreto a Dios, expresado en generosidad y servicio. Gracias por tu ayuda.]

#let oracion_colecta = [Señor Dios, que manifiestas tu poder de una manera admirable sobre todo cuando perdonas y ejerces tu misericordia, multiplica tu gracia sobre nosotros, para que, apresurándonos hacia lo que nos prometes, nos hagas partícipes de los bienes celestiales. Por nuestro Señor Jesucristo, tu Hijo, que vive y reina contigo en la unidad del Espíritu Santo y es Dios por los siglos de los siglos.]
#let lectura_primera_fuente = [Del libro del profeta Ezequiel 18, 25-28.]
#let lectura_primera = [
  Esto dice el Señor: “Si ustedes dicen: ‘No es justo el proceder del Señor’, escucha , casa de Israel: ¿Conque es injusto mi proceder? ¿No es más bien el proceder de ustedes el injusto?

  Cuando el justo se aparta de su justicia, comete la maldad y muere; muere por la maldad que cometió. Cuando el pecador se arrepiente del mal que hizo y practica la rectitud y la justicia, él mismo salva su vida. Si recapacita y se aparta de los delitos cometidos, ciertamente vivirá y no morirá”.
]
#let salmo_fuente = "Del salmo 24."
#let salmo_partitura = "para-misales/20260927-salmo.png"
#let salmo_aclamacion = "Descúbrenos, Señor, tus caminos."
#let salmo_estrofas = (
  [
    Descúbrenos, Señor, tus caminos,
    guíanos con la verdad de tu doctrina.
    Tú eres nuestro Dios y salvador
    y tenemos en ti nuestra esperanza.
],
  [
    Acuérdate, Señor, que son eternos
    tu amor y tu ternura.
    Según ese amor y esa ternura,
    acuérdate de nosotros.
],
  [
    Porque el Señor es recto y bondadoso
    indica a los pecadores el sendero,
    guía por la senda recta a los humildes
    y descubre a los pobres sus caminos.
],
)
#let lectura_segunda_fuente = [De la carta del apóstol san Pablo a los filipenses 2, 1-11.]
#let lectura_segunda = [
  Hermanos: Si alguna fuerza tiene una advertencia en nombre de Cristo, si de algo sirve una exhortación nacida del amor, si nos une el mismo Espíritu y si ustedes me profesan un afecto entrañable, llénenme de alegría teniendo todos una misma manera de pensar, un mismo amor, unas mismas aspiraciones y una sola alma. Nada hagan por espíritu de rivalidad ni presunción; antes bien, por humildad, cada uno considere a los demás como superiores a sí mismo y no busque su propio interés, sino el del prójimo. Tengan los mismos sentimientos que tuvo Cristo Jesús.

  Cristo, siendo Dios, no consideró que debía aferrarse a las prerrogativas de su condición divina, sino que, por el contrario, se anonadó a sí mismo, tomando la condición de siervo, y se hizo semejante a los hombres. Así, hecho uno de ellos, se humilló a sí mismo y por obediencia aceptó incluso la muerte y una muerte de cruz.

  Por eso Dios lo exaltó sobre todas las cosas y le otorgó el nombre que está sobre todo nombre, para que al nombre de Jesús, todos doblen la rodilla en el cielo, en la tierra y en los abismos, y todos reconozcan públicamente que Jesucristo es el Señor, para gloria de Dios Padre.
]
#let aleluya_aclamacion = [Mis ovejas escuchan mi voz, dice el Señor; yo las conozco y ellas me siguen.]
#let evangelio_fuente = [Del santo evangelio según san Mateo: 21, 28-32.]
#let evangelio = [
  En aquel tiempo, Jesús dijo a los sumos sacerdotes y a los ancianos del pueblo: ¿Qué opinan de esto? Un hombre tenía dos hijos fue a ver al primero y le ordenó: ‘Hijo, ve a trabajar hoy en la viña’. El le contestó: ‘Ya voy, señor’, pero no fue. El padre se dirigió al segundo y le dijo lo mismo. Este le respondió: ‘No quiero ir’, pero se arrepintió y fue. ¿Cuál de los dos hizo la voluntad del padre?” Ellos le respondieron: “El segundo”.

  Entonces Jesús les dijo: “Yo les aseguro que los publicanos y las prostitutas se les han adelantado en el camino del Reino de Dios. Porque vino a ustedes Juan, predicó el camino de la justicia y no le creyeron; en cambio, los publicanos y las prostitutas, sí le creyeron; ustedes, ni siquiera después de haber visto, se han arrepentido ni han creído en él”.
]
#let oracion_delosfieles = [
  Sacerdote: Hermanos, Dios no se cansa de llamarnos a la conversión y nos da siempre la oportunidad de comenzar de nuevo. Con confianza presentemos nuestras súplicas.

  Todos: Señor, ayúdanos a vivir conforme a tu voluntad.

  Lector: Pidamos por la Iglesia, para que su anuncio del Evangelio esté siempre acompañado por un testimonio auténtico de vida.

  Todos: Señor, líbranos de una fe hecha solamente de palabras y haz de tu Iglesia una comunidad coherente y siempre dispuesta a convertirse.

  Lector: Pidamos por quienes inician en el contienda electoral del próximo año, para que sus compromisos no se queden solamente en discursos o promesas.

  Todos: Señor, dales honestidad y constancia para cumplir aquello que favorezca la justicia, la dignidad humana, la paz y el verdadero bien común.

  Lector: Pidamos por quienes sienten que han tomado malas decisiones o se han alejado de Dios y piensan que ya es demasiado tarde para regresar.

  Todos: Señor, hazles experimentar tu misericordia y recuérdales que siempre existe la posibilidad de cambiar, volver a Ti y comenzar una vida nueva.

  Lector: Pidamos por los jóvenes y universitarios, para que aprendan a vivir con coherencia entre lo que creen, lo que dicen y las decisiones que toman cada día.

  Todos: Señor, dales libertad interior, responsabilidad y valentía para elegir el bien, incluso cuando implique esfuerzo, renuncia o ir contra corriente.

  Lector: En este Tiempo de la Creación, pidamos por quienes trabajan en la defensa y cuidado de nuestra casa común.

  Todos: Señor, convierte nuestros buenos deseos en hábitos concretos de cuidado, responsabilidad y gratitud por la creación que has puesto en nuestras manos.

  Lector: Pidamos por nuestra comunidad de San Juan Bosco,”camino de encuentro que forma discípulos”, para que nuestra fe produzca frutos visibles de servicio y misericordia.

  Todos: Señor, enséñanos a pasar de las buenas intenciones al compromiso concreto, sirviendo con alegría y haciendo de nuestra parroquia un hogar donde otros puedan encontrarte.

  Lector: Pidamos por quienes están discerniendo su vocación y sienten que Dios los invita a dar un paso más en su seguimiento.

  Todos: Señor, dales generosidad para responderte no solamente con palabras, sino con decisiones concretas y una vida entregada al servicio de los demás.

  Sacerdote: Padre misericordioso, Tú conoces nuestro corazón y nunca te cansas de invitarnos a volver a Ti. Escucha nuestras súplicas y concédenos la gracia de cumplir con alegría tu voluntad. Por Jesucristo nuestro Señor.

  Todos: Amén.
]
#let oracion_ofrendas = [
  Concédenos, Dios misericordioso, que nuestra ofrenda te sea aceptable y que por ella quede abierta para nosotros la fuente de toda bendición. Por Jesucristo, nuestro Señor.
]
#let oracion_comunion = [
  Que este misterio celestial renueve, Señor, nuestro cuerpo y nuestro espíritu, para que seamos coherederos en la gloria de aquel cuya muerte, al anunciarla, la hemos compartido. Él, que vive y reina por los siglos de los siglos.
]
#let oracion_personal = [
  Jesús, hoy me haces una pregunta muy concreta: ¿digo que sí solamente con mis palabras, o realmente hago la voluntad del Padre? Reconozco que muchas veces tengo buenas intenciones. Prometo cambiar, servir más, rezar mejor, perdonar o dedicar tiempo a lo verdaderamente importante… pero después dejo que la comodidad, las distracciones o el miedo decidan por mí.

  Gracias porque Tú no me defines por mis incoherencias. Gracias porque, como al hijo del Evangelio, me das la oportunidad de recapacitar, volver y comenzar nuevamente. Hoy te pido que hagas mi fe más concreta. Que mis palabras coincidan cada vez más con mis decisiones. Ayúdame a ser coherente en mi familia, mis amistades, mi trabajo, mis estudios y mi servicio.

  Dame humildad para reconocer cuando he dicho “no” con mi vida y valentía para cambiar de dirección. Jesús, quiero que mi respuesta a Ti sea verdadera. Que cuando diga «sí», ese sí pueda verse en mi manera de amar. Te alabo y te doy gracias porque nunca te cansas de darme otra oportunidad. Amén.
]
